version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: IDisposableAnalyzers
    versions:
    - 3.4.10
    - 3.4.11
    - 3.4.8
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
