language: csharp
solution: paspaspas.sln
mono: none
dotnet: 2.2.101
dist: xenial
script:
 - cd PasPasPasTests
 - dotnet restore
 - dotnet test
before_install:
  - pip install --user codecov
after_success:
 - codecov