//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3SyntaxTreeViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3SyntaxTreeViewer.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token.
        /// </summary>
        internal static string m_05d3bbe032e243eb850bebdb2b7ef272 {
            get {
                return ResourceManager.GetString("m_05d3bbe032e243eb850bebdb2b7ef272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared Field.
        /// </summary>
        internal static string m_8165f2988eb84cd28547752d9d2ed624 {
            get {
                return ResourceManager.GetString("m_8165f2988eb84cd28547752d9d2ed624", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing token.
        /// </summary>
        internal static string m_9fb11f842fe3489cb715dd29458e434e {
            get {
                return ResourceManager.GetString("m_9fb11f842fe3489cb715dd29458e434e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared Symbol.
        /// </summary>
        internal static string m_bd36c92cbacf492c8bf817e890cbaafa {
            get {
                return ResourceManager.GetString("m_bd36c92cbacf492c8bf817e890cbaafa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared Parameter.
        /// </summary>
        internal static string m_c795d660c7a44bce8af426235295bf3d {
            get {
                return ResourceManager.GetString("m_c795d660c7a44bce8af426235295bf3d", resourceCulture);
            }
        }
    }
}
