//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3SyntaxTreeViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3SyntaxTreeViewer.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token.
        /// </summary>
        internal static string m_0101 {
            get {
                return ResourceManager.GetString("m_0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User message.
        /// </summary>
        internal static string m_0102 {
            get {
                return ResourceManager.GetString("m_0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing token.
        /// </summary>
        internal static string m_0103 {
            get {
                return ResourceManager.GetString("m_0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file.
        /// </summary>
        internal static string m_0104 {
            get {
                return ResourceManager.GetString("m_0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Unit.
        /// </summary>
        internal static string m_0350 {
            get {
                return ResourceManager.GetString("m_0350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name does not match file name.
        /// </summary>
        internal static string m_0351 {
            get {
                return ResourceManager.GetString("m_0351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared unit name in uses list.
        /// </summary>
        internal static string m_0352 {
            get {
                return ResourceManager.GetString("m_0352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared Symbol.
        /// </summary>
        internal static string m_0353 {
            get {
                return ResourceManager.GetString("m_0353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared enum name.
        /// </summary>
        internal static string m_0354 {
            get {
                return ResourceManager.GetString("m_0354", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type of.
        /// </summary>
        internal static string m_0355 {
            get {
                return ResourceManager.GetString("m_0355", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared Parameter.
        /// </summary>
        internal static string m_0356 {
            get {
                return ResourceManager.GetString("m_0356", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclared Field.
        /// </summary>
        internal static string m_0357 {
            get {
                return ResourceManager.GetString("m_0357", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character.
        /// </summary>
        internal static string m_0390 {
            get {
                return ResourceManager.GetString("m_0390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of token.
        /// </summary>
        internal static string m_0391 {
            get {
                return ResourceManager.GetString("m_0391", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete hex number.
        /// </summary>
        internal static string m_0392 {
            get {
                return ResourceManager.GetString("m_0392", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete identifier.
        /// </summary>
        internal static string m_0393 {
            get {
                return ResourceManager.GetString("m_0393", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete string.
        /// </summary>
        internal static string m_0394 {
            get {
                return ResourceManager.GetString("m_0394", resourceCulture);
            }
        }
    }
}
