// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.TypeAnnotator.GetErrorType(PasPasPas.Parsing.SyntaxTree.Types.ITypedSyntaxNode)~PasPasPas.Globals.Types.ITypeDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.TypeAnnotator.GetErrorTypeReference(PasPasPas.Parsing.SyntaxTree.Types.ITypedSyntaxNode)~PasPasPas.Globals.Runtime.ITypeReference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.TypeAnnotator.GetErrorTypeReference(PasPasPas.Parsing.SyntaxTree.Types.ITypedSyntaxNode)~PasPasPas.Globals.Runtime.ITypeReference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypes.CastCharTo(System.Int32,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypes.CastIntTo(System.Int32,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1502:Avoid excessive complexity", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypesHelper.GetOperatorId(PasPasPas.Globals.Types.ITypeRegistry,PasPasPas.Parsing.SyntaxTree.Abstract.ExpressionKind,PasPasPas.Globals.Runtime.ITypeReference,PasPasPas.Globals.Runtime.ITypeReference)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1506:Avoid excessive class coupling", Justification = "<Pending>", Scope = "type", Target = "~T:PasPasPas.Typings.Common.TypeAnnotator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypes.CastBooleanTo(System.Int32,System.Int32)~System.Int32")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1502:Avoid excessive complexity", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.TypeAnnotator.EndVisit(PasPasPas.Parsing.SyntaxTree.Abstract.SymbolReference)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1502:Avoid excessive complexity", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypesHelper.GetSmallestIntegralTypeOrNext(PasPasPas.Globals.Types.ITypeRegistry,System.Int32,System.Int32,System.Int32,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1502:Avoid excessive complexity", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.Resolver.ResolveByName(PasPasPas.Globals.Runtime.ITypeReference,System.String,System.Int32)~PasPasPas.Globals.Types.Reference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1502:Avoid excessive complexity", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.Resolver.ResolveByName(PasPasPas.Globals.Runtime.ITypeReference,System.String,System.Int32,PasPasPas.Typings.Common.ResolverFlags)~PasPasPas.Globals.Types.Reference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1502:Avoid excessive complexity", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.TypeAnnotator.DetermineSymbolTypes(PasPasPas.Parsing.SyntaxTree.Abstract.SymbolReference)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.TypeAnnotator.GetErrorType(PasPasPas.Parsing.SyntaxTree.Types.ITypedSyntaxNode)~PasPasPas.Globals.Types.ITypeDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CA1502:Avoid excessive complexity", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypesHelper.GetSmallestIntegralTypeOrNext(PasPasPas.Globals.Types.ITypeRegistry,PasPasPas.Globals.Types.ITypeDefinition,PasPasPas.Globals.Types.ITypeDefinition,System.Int32,System.Boolean)~PasPasPas.Globals.Types.ITypeDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypesHelper.GetOperatorId(PasPasPas.Globals.Types.ITypeRegistry,PasPasPas.Parsing.SyntaxTree.Abstract.ExpressionKind,PasPasPas.Globals.Types.ITypeSymbol,PasPasPas.Globals.Types.ITypeSymbol)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Common.RegisteredTypesHelper.GetOperatorId(PasPasPas.Globals.Types.ITypeRegistry,PasPasPas.Parsing.SyntaxTree.Abstract.ExpressionKind,PasPasPas.Globals.Types.ITypeSymbol,PasPasPas.Globals.Types.ITypeSymbol)~PasPasPas.Globals.Types.OperatorKind")]
[assembly: SuppressMessage("CodeSmell", "EPC11:Suspicious equality implementation: no instance members are used.", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Hidden.ErrorType.Equals(PasPasPas.Globals.Types.ITypeDefinition)~System.Boolean")]
[assembly: SuppressMessage("CodeSmell", "EPC11:Suspicious equality implementation: no instance members are used.", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Simple.AnsiCharType.Equals(PasPasPas.Globals.Types.ITypeDefinition)~System.Boolean")]
[assembly: SuppressMessage("CodeSmell", "EPC11:Suspicious equality implementation: no instance members are used.", Justification = "<Pending>", Scope = "member", Target = "~M:PasPasPas.Typings.Structured.RoutineType.Equals(PasPasPas.Globals.Types.ITypeDefinition)~System.Boolean")]
